HOSTS:
  server:
    roles:
      - default
      - server
    yum_repos:
      simp:
        baseurl: https://packagecloud.io/simp-project/6_X_Alpha_Dependencies/el/7/$basearch
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  #  box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
  # slave1:
  #   roles:
  #     - slave
  #   platform:   el-7-x86_64
  #   box:        puppetlabs/centos-7.0-64-nocm
  #   box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
  #   hypervisor: vagrant
  # slave2:
  #   roles:
  #     - slave
  #   platform:   el-7-x86_64
  #   box:        puppetlabs/centos-7.0-64-nocm
  #   box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.0-64-nocm
  #   hypervisor: vagrant
CONFIG:
  log_level:       verbose
  type:            aio
  vagrant_memsize: 256
