HOSTS:
  server-el7:
    roles:
      - default
      - server
    yum_repos:
      simp:
        baseurl: https://packagecloud.io/simp-project/6_X_Alpha_Dependencies/el/7/$basearch
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  server-el6:
    roles:
      - server
    yum_repos:
      simp:
        baseurl: https://packagecloud.io/simp-project/6_X_Alpha_Dependencies/el/7/$basearch
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
  # slave-el7:
  #   roles:
  #     - slave
  #   platform:   el-7-x86_64
  #   box:        centos/7
  #   hypervisor: vagrant
  # slave-el6:
  #   roles:
  #     - slave
  #   platform:   el-6-x86_64
  #   box:        centos/6
  #   hypervisor: vagrant
CONFIG:
  log_level:       verbose
  type:            aio
  vagrant_memsize: 256
  synced_folder:   disabled