<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  # NOTE: Node names are used in the tests
  yggdrasil:
    roles:
      - default
      - ldap_root
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

  valhalla:
    roles:
      - ldap_replica
      - valhalla
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

  niflheim:
    roles:
      - ldap_replica
      - niflheim
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

CONFIG:
  type: aio
  vagrant_memsize: 256
  log_level: verbose
  synced_folder: disabled
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
